export const en = {
  nav: {
    about: 'About',
    skills: 'Skills',
    projects: 'Projects',
    experience: 'Experience',
    blog: 'Blog',
    contact: 'Contact',
    resume: 'Resume',
  },
  hero: {
    greeting: "Hey, I'm",
    name: 'Furkan Paşaoğlu',
    subtitle: 'Senior Software Developer',
    desc: 'I have worked on more than 30 enterprise projects, developing web and backend systems running in production environments. Within the .NET ecosystem, I focus on web applications, service-oriented architectures, system integrations, and automation processes.',
    cta1: 'View My Projects',
    cta2: 'Get In Touch',
  },
  about: {
    tag: '// about',
    title: 'About',
    p1: `Hi! I'm Furkan — a .NET Backend Developer building enterprise-scale systems actively used in real-world environments. I have taken part in more than 30 projects, contributing to web and backend solutions.`,
    p2: 'Within the ASP.NET and .NET Core ecosystem, I develop service-oriented architectures, system integrations, and sustainable backend solutions. I have designed and implemented integration solutions across different industries. I also have experience with CI/CD processes and live system operations.',
    p3: 'I value clean code principles and focus on building performance-driven and maintainable systems. I actively contribute to development processes and take technical responsibility within teams.',
    cta1: 'Let’s Work Together',
    cta2: 'Download Resume',
    stats: [
      { label: '2021', desc: 'Professional Career Start' },
      { label: '30+', desc: 'Enterprise Projects' },
      { label: '.NET / C#', desc: 'Core Expertise' },
      { label: 'Backend & AI', desc: 'Primary Focus' }
    ],
  },
  skills: {
    tag: '// tech stack',
    title: 'Skills',
    desc: 'Technologies and tools I actively use in enterprise software development.',
    tiers: { expert: 'Expert', proficient: 'Proficient', familiar: 'Familiar' },
  },
  projects: {
    tag: '// selected work',
    title: 'Projects',
    desc: 'Selected enterprise and open-source projects built across various industries.',
    viewGithub: 'View All Projects on GitHub',
    modal: {
      techStack: 'Tech Stack',
      highlights: 'Highlights',
      github: 'View on GitHub',
      live: 'View Live',
      close: 'Close',
      status: 'Status',
      type: 'Type',
    },
  },
  experience: {
    tag: '// work history',
    title: 'Experience',
    desc: 'My professional career journey in enterprise software development.',
    modal: {
      highlights: 'Highlights',
      techStack: 'Tech Stack',
      close: 'Close',
    },
  },
  blog: {
    tag: '// articles',
    title: 'Blog',
    desc: 'Technical articles I wrote on .NET, distributed systems, and modern software development.',
    readMore: 'Read More',
    minRead: 'min read',
    allPosts: 'View All Posts',
    categories: { all: 'All' },
  },
  contact: {
    tag: '// get in touch',
    title: 'Contact',
    desc: 'Feel free to reach out for new projects, collaboration opportunities, or just to say hello.',
    email: 'Email',
    location: 'Location',
    locationValue: 'Istanbul, Turkey',
    available: 'Available for Freelance / Part-time projects',
    name: 'Name',
    emailLabel: 'Email',
    message: 'Message',
    namePlaceholder: 'Your Full Name',
    emailPlaceholder: 'email@example.com',
    messagePlaceholder: 'Tell me about your project or collaboration idea...',
    send: 'Send Message',
    sent: '✓ Message Sent!',
  },
  footer: {
    made: 'made by',
  },
  loading: {
    lines: ['Initializing System...', 'Loading Modules...', 'Getting Ready...'],
  },
  common: {
    details: 'Details',
    back: 'Back',
    close: 'Close',
    searchPlaceholder: 'Search articles...',
    noResults: 'No results found.',
  },
};
