export const tr = {
  nav: {
    about: 'Hakkımda',
    skills: 'Yetenekler',
    projects: 'Projeler',
    experience: 'Deneyim',
    blog: 'Blog',
    contact: 'İletişim',
    resume: 'CV',
  },
  hero: {
    greeting: 'Merhaba, Ben',
    name: 'Furkan Paşaoğlu',
    subtitle: 'Senior Software Developer',
    desc: '30’dan fazla kurumsal projede üretim ortamında çalışan web ve backend sistemler geliştirdim. .NET ekosisteminde web uygulamaları, servis tabanlı mimariler, entegrasyon çözümleri ve otomasyon süreçleri üzerine çalışıyorum.',
    cta1: 'Projelerimi Gör',
    cta2: 'İletişime Geç',
  },
  about: {
    tag: '// hakkımda',
    title: 'Hakkımda',
    p1: `Merhaba! Ben Furkan — kurumsal ölçekte aktif olarak kullanılan sistemler geliştiren bir .NET Backend Developer’ım. 30’dan fazla projede web ve backend çözümler üzerinde aktif rol aldım.`,
    p2: 'ASP.NET ve .NET Core ekosisteminde servis tabanlı mimariler, sistem entegrasyonları ve sürdürülebilir backend çözümleri geliştiriyorum. Farklı sektörlerde ihtiyaçlara uygun entegrasyon çözümleri tasarladım ve uyguladım. CI/CD süreçleri ve canlı sistem operasyonlarında deneyim sahibiyim.',
    p3: 'Temiz kod prensiplerine önem veriyor, performans ve sürdürülebilirlik odaklı sistemler tasarlıyorum. Takım içinde teknik sorumluluk alarak geliştirme süreçlerine katkı sağlıyorum.',
    cta1: 'Seninle Çalışalım',
    cta2: 'CV İndir',
    stats: [
      { label: '2021', desc: 'Profesyonel Kariyer Başlangıcı' },
      { label: '30+', desc: 'Kurumsal Proje Deneyimi' },
      { label: '.NET / C#', desc: 'Ana Uzmanlık Alanı' },
      { label: 'Backend & Yapay Zeka', desc: 'Odak Alanı' }
    ],
  },
  skills: {
    tag: '// teknoloji yığını',
    title: 'Yetenekler',
    desc: 'Kurumsal yazılım geliştirme sürecinde aktif olarak kullandığım teknolojiler ve araçlar.',
    tiers: { expert: 'Uzman', proficient: 'Yetkin', familiar: 'Öğreniliyor' },
  },
  projects: {
    tag: '// seçilen çalışmalar',
    title: 'Projeler',
    desc: 'Çeşitli sektörler için geliştirdiğim kurumsal ve açık kaynak projelerden seçkiler.',
    viewGithub: "Tüm Projeleri GitHub'da Gör",
    modal: {
      techStack: 'Teknoloji Yığını',
      highlights: 'Öne Çıkanlar',
      github: 'GitHub\'da Gör',
      live: 'Canlıyı Gör',
      close: 'Kapat',
      status: 'Durum',
      type: 'Tip',
    },
  },
  experience: {
    tag: '// kariyer geçmişi',
    title: 'Deneyim',
    desc: 'Kurumsal yazılım geliştirme alanındaki profesyonel kariyer yolculuğum.',
    modal: {
      highlights: 'Öne Çıkanlar',
      techStack: 'Teknoloji Yığını',
      close: 'Kapat',
    },
  },
  blog: {
    tag: '// yazılar',
    title: 'Blog',
    desc: '.NET, dağıtık sistemler ve modern yazılım geliştirme üzerine yazdığım teknik yazılar.',
    readMore: 'Devamını Oku',
    minRead: 'dk okuma',
    allPosts: 'Tüm Yazıları Gör',
    categories: { all: 'Tümü' },
  },
  contact: {
    tag: '// iletişim',
    title: 'İletişim',
    desc: 'Yeni projeler, iş birliği fırsatları veya sadece bir selamlama için benimle iletişime geçebilirsin.',
    email: 'Email',
    location: 'Lokasyon',
    locationValue: 'İstanbul, Türkiye',
    available: 'Freelance / Part-time projeler için müsait',
    name: 'İsim',
    emailLabel: 'Email',
    message: 'Mesaj',
    namePlaceholder: 'Adınız Soyadınız',
    emailPlaceholder: 'email@ornek.com',
    messagePlaceholder: 'Projeniz veya iş birliği teklifiniz hakkında bilgi verin...',
    send: 'Mesaj Gönder',
    sent: '✓ Mesaj Gönderildi!',
  },
  footer: {
    made: 'tarafından yapıldı',
  },
  loading: {
    lines: ['Sistem Başlatılıyor...', 'Modüller Yükleniyor...', 'Hazırlanıyor...'],
  },
};
